dist: bionic
language: ruby
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-9.2.11.1
jobs:
  allow_failures:
  - rvm: jruby-9.2.11.1
cache: bundler
notifications:
  email: false
